-- CreateTable
CREATE TABLE "Venue" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "postalCode" TEXT NOT NULL,
    "cityName" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "pricePerNightInEUR" INTEGER NOT NULL,
    "rating" DOUBLE PRECISION NOT NULL,
    "numberOfReviews" INTEGER NOT NULL,
    "capacity" INTEGER NOT NULL,
    "amountOfBeds" INTEGER NOT NULL,
    "description" TEXT NOT NULL,
    "checkInHour" TEXT NOT NULL,
    "checkOutHour" TEXT NOT NULL,
    "metersFromCityCenter" INTEGER NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "fireplace" BOOLEAN NOT NULL,
    "speakers" BOOLEAN NOT NULL,
    "wiFi" BOOLEAN NOT NULL,
    "restaurantInHouse" BOOLEAN NOT NULL,
    "bar" BOOLEAN NOT NULL,
    "pool" BOOLEAN NOT NULL,
    "jacuzzi" BOOLEAN NOT NULL,
    "garden" BOOLEAN NOT NULL,
    "fitnessCenter" BOOLEAN NOT NULL,
    "reception24H" BOOLEAN NOT NULL,
    "karaoke" BOOLEAN NOT NULL,
    "outdoorMusic" BOOLEAN NOT NULL,
    "indoorMusic" BOOLEAN NOT NULL,
    "library" BOOLEAN NOT NULL,
    "petFriendly" BOOLEAN NOT NULL,
    "parking" BOOLEAN NOT NULL,
    "playground" BOOLEAN NOT NULL,
    "kitchen" BOOLEAN NOT NULL,
    "bathroom" BOOLEAN NOT NULL,
    "hypoallergenicBedding" BOOLEAN NOT NULL,
    "tv" BOOLEAN NOT NULL,
    "safe" BOOLEAN NOT NULL,
    "wheelchairFriendly" BOOLEAN NOT NULL,
    "shortGrownFriendly" BOOLEAN NOT NULL,
    "blindFriendly" BOOLEAN NOT NULL,
    "deafFriendly" BOOLEAN NOT NULL,
    "lakeNearby" BOOLEAN NOT NULL,
    "forestNearby" BOOLEAN NOT NULL,
    "mountainsNearby" BOOLEAN NOT NULL,
    "seaNearby" BOOLEAN NOT NULL,
    "nationalParkNearby" BOOLEAN NOT NULL,
    "parkNearby" BOOLEAN NOT NULL,
    "mallNearby" BOOLEAN NOT NULL,
    "zooNearby" BOOLEAN NOT NULL,
    "churchNearby" BOOLEAN NOT NULL,
    "oldTownNearby" BOOLEAN NOT NULL,
    "monumentNearby" BOOLEAN NOT NULL,
    "museumNearby" BOOLEAN NOT NULL,
    "theatreNearby" BOOLEAN NOT NULL,
    "cinemaNearby" BOOLEAN NOT NULL,
    "amusementParkNearby" BOOLEAN NOT NULL,
    "restaurantNearby" BOOLEAN NOT NULL,

    CONSTRAINT "Venue_pkey" PRIMARY KEY ("id")
);
